// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class EnemyGenerator : MonoBehaviour 
{
	public GameObject enemyPrefab;

	void Update(){
		GameObject enemy = Instantiate (enemyPrefab);

		enemy.transform.position = new Vector3 (10, 10, 0);
	}
}


